### ISSUE TITLE
WASM build

### ISSUE THREAD

**Issue by hrgdavor** [CADmium-Co/ISOtope#9]
This package looks promising and could find use outside of CADmium. would be nice to play with from JS.

**Comment by TobiasJacob** [comment]
Hi @hrgdavor ,

can you take a look at the current state of the project and if it fulfills your needs? All important structs have 

```rust
#[derive(Debug, Clone, PartialEq, PartialOrd, Serialize, Deserialize)]
#[cfg_attr(feature = "tsify", derive(Tsify))]
#[cfg_attr(feature = "tsify", tsify(into_wasm_abi, from_wasm_abi))]
```

**Comment by avaziman** [comment]
To use the project in JS, we would need to export the functions to JS using wasm-bindgen which will generate the bridging interface.

This requires some changes since the critical functions to export, are taking parameters of Rc<Refcell<T>> which cannot be transferred to JS, so some kind of wrapper types are required not to expose the reference counters directly.

I am happily picking this issue up since I would like to try it out on my project.

**Comment by hrgdavor** [comment]
> I am happily picking this issue up since I would like to try it out on my project.

That would be cool, I can only try it out once WASM and binding is generated, I have no experience exporting stuff to WASM:

**Comment by avaziman** [comment]
hey I managed to port it to wasm on this branch https://github.com/avaziman/ISOtope/tree/wasm/web , you are welcome to try out,  example on how to use with vanilla js is on web.html in root.

**Comment by hrgdavor** [comment]
ugh, that would mean I need to know how to build it on windows. exported example with built js and wasm would be easier :) ... maybe building it is not too hard, just have not done it yet for any rust project, I have zero setup.

**Comment by avaziman** [comment]
Hey no problem, all you need is to run:
wasm-pack build --features=tsify --target=web
which will build the WASM and then just serve the web.html file,
can easily be done by 
npm install --global http-server
then run
http-server

**Comment by hrgdavor** [comment]
[INFO]: Compiling to Wasm...
error: unexpected argument '--platform' found

**Comment by avaziman** [comment]
hey my bad, its target, updated the instructions

**Comment by hrgdavor** [comment]
works !

:) nice
![image](https://github.com/user-attachments/assets/e839e366-ccac-447e-9386-c72b7b78e30f)

**Comment by avaziman** [comment]
glad it works, I actually found out about planegcs which has a port to WASM https://github.com/Salusoft89/planegcs which suits my needs better than this library currently because it contains more constraint types, so it might be of use to you to, its the geometric solver used by FreeCAD.
Because of this I won't continue working on this projects WASM port unfortunately but hope I helped.

**Comment by hrgdavor** [comment]
I am also subscribed to notifications on planegcs. Currently am only watching things in this area of constraint solving, projects with constraint solving are bit more further on my todo :)

It would be nice to see if you are building sth public, what you create with it :).
I am also on cadmium and cadhub discord server.
